# frontend/Dockerfile.dev
FROM node:24.12.0 AS build
WORKDIR /app

# Install deps (use lockfile if you have it)
COPY package.json package-lock.json* ./
RUN npm ci || npm install
    
# Build Vite app -> /app/dist
COPY . .
RUN npm run build
    
# ---- runtime stage ----
FROM nginx:stable-alpine
    
# Serve the built static files
COPY --from=build /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/nginx.conf
    
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
    