from collections import defaultdict
import json
import os
from src.repositories.database import db
from .models import (
    CheckpointGrades,
    MainAssignmentGrades,
    Projects,
    StudentSuggestions,
    SubmissionAnnotations,
    Submissions,
    Users,
)
from sqlalchemy import desc, and_
from typing import Dict, List
from datetime import datetime

class SubmissionRepository:

    def get_submission_by_user_and_projectid(self, user_id:int, project_id: int)-> Submissions:
        """Returns the latest submission made by a user for a given project.

        Args:
            user_id (int): The ID of the user.
            project_id (int): The ID of the project.

        Returns:
            Submissions: The latest submission object made by the user for the given project.
        """

        # MAIN submissions only (exclude checkpoint submissions that share the same Project id)
        submission = (
            Submissions.query
            .filter(and_(
                Submissions.Project == project_id,
                Submissions.User == user_id,
                Submissions.IsCheckpoint == False
            ))
            .order_by(desc("Time"))
            .first()
        )

        return submission

    def get_submission_by_submission_id(self, submission_id: int) -> Submissions:
        """Retrieves a submission by its ID.

        Args:
            submission_id (int): The ID of the submission to retrieve.

        Returns:
            Submissions: The submission object with the specified ID.
        """
        submission = Submissions.query.filter(Submissions.Id == submission_id).order_by(desc("Time")).first()
        return submission

    def get_code_path_by_submission_id(self, submission_id: int) -> str:
        """Returns the file path of the code file associated with a submission.

        Args:
            submission_id (int): The ID of the submission.

        Returns:
            str: The file path of the code file associated with the submission.
        """
        submission = self.get_submission_by_submission_id(submission_id)
        return submission.CodeFilepath

    def read_code_file(self, code_path) -> str:
        """Returns the contents of the code file associated with a given submission.

        Args:
            submission_id (int): The ID of the submission.

        Returns:
            str: The contents of the code file associated with the submission.
        """
        student_file = ""
        #TODO: Make More Robust for Multiple Files, this simply grabs the first file in the directory
        if os.path.isdir(code_path):
            for filename in os.listdir(code_path):
                with open(filename, "r") as f:
                    student_file = f.read()
                break
        else:
            with open(code_path, "r") as f:
                student_file = f.read()
        return student_file
        
    def read_output_file(self, output_path) -> str:
        """Returns the contents of the output file associated with a given submission.

        Args:
            submission_id (int): The ID of the submission.

        Returns:
            str: The contents of the output file associated with the submission.
        """
        student_output_file = ""
        with open(output_path, "r") as f:
            student_output_file = f.read()
        return student_output_file
    
    def create_submission(
        self,
        user_id: int,
        output: str,
        codepath: str,
        time: str,
        project_id: int,
        status: bool,
        testcase_results,
        is_checkpoint: bool = False,
        checkpoint_id: int = None,
        submission_method: str = "unknown",
    ):
        """Creates a new submission record in the database.

        Args:
            user_id (int): The ID of the user who submitted the code.
            output (str): The filepath of the output file generated by the code.
            codepath (str): The filepath of the code file submitted.
            time (str): The time at which the submission was made.
            project_id (int): The ID of the project for which the code was submitted.
            status (bool): Whether the submission passed or failed.
            testcase_results: The testcase results produced by the grader.
            is_checkpoint (bool): Whether this is a checkpoint submission.
            checkpoint_id (int): The checkpoint ID when this is a checkpoint submission.
            submission_method (str): How the student supplied the program: "upload", "editor", or "unknown".

        Returns:
            int: The ID of the newly created submission record.
        """
        submission = Submissions(
            OutputFilepath=output,
            CodeFilepath=codepath,
            Time=time,
            User=user_id,
            Project=project_id,
            IsPassing=status,
            IsCheckpoint=bool(is_checkpoint),
            CheckpointId=(int(checkpoint_id) if (is_checkpoint and checkpoint_id is not None) else None),
            SubmissionMethod=submission_method,
            TestCaseResults=str(testcase_results),
        )
        db.session.add(submission)
        db.session.commit()
        created_id = submission.Id  # Assuming the auto-incremented ID field is named "ID"
        return created_id

    def get_total_submission_for_all_projects(self) -> Dict[int, int]:
        """
        Returns a dictionary containing the total number of unique submissions for each project.

        Returns:
        - A dictionary where the keys are project IDs and the values are the total number of unique submissions for that project.
        """
        thisdic={}
        project_ids = Projects.query.with_entities(Projects.Id).all()
        for proj in project_ids:
            count = (
                Submissions.query.with_entities(Submissions.User)
                .filter(Submissions.Project == proj[0], Submissions.IsCheckpoint == False)
                .distinct()
                .count()
            )
            thisdic[proj[0]]=count
        return thisdic

    def get_most_recent_submission_by_project(self, project_id: int, user_ids: List[int]) -> Dict[int, Submissions]:
        """
        Returns a dictionary containing the most recent submission for each user in a given project.

        Args:
            project_id (int): The ID of the project to search for submissions.
            user_ids (List[int]): A list of user IDs to search for submissions.

        Returns:
            Dict[int, Submissions]: A dictionary where the keys are user IDs and the values are the most recent submission for each user.
        """

        holder = (
            Submissions.query
            .filter(and_(
                Submissions.Project == project_id,
                Submissions.User.in_(user_ids),
                Submissions.IsCheckpoint == False
            ))
            .order_by(desc(Submissions.Time))
            .all()
        )

        bucket={}
        for obj in holder:
            if obj.User in bucket:
                if bucket[obj.User].Time < obj.Time:
                    bucket[obj.User] = obj
                else:
                    pass
            else:
                bucket[obj.User] = obj
        return bucket

    def submission_view_verification(self, user_id, submission_id) -> bool:
        submission = Submissions.query.filter(and_(Submissions.Id==submission_id,Submissions.User==user_id)).first()
        return submission is not None
        
    def unlock_check(self, user_id,project_id) -> bool:
        # Legacy unlocks were removed in the checkpoint system.
        return False
        
    def submission_counter(self, project_id: int, user_ids: List[int]) -> bool:

        submissions = (
            Submissions.query
            .filter(and_(
                Submissions.Project == project_id,
                Submissions.User.in_(user_ids),
                Submissions.IsCheckpoint == False
            ))
            .all()
        )

        submission_counter_dict={}
        for sub in submissions:
            if sub.User in submission_counter_dict:
                submission_counter_dict[sub.User] = submission_counter_dict[sub.User] +1
            else:
                submission_counter_dict[sub.User] = 1
        return submission_counter_dict

    def get_all_submissions_for_project(self, project_id):
        submissions = Submissions.query.filter(Submissions.Project == project_id).all()
        return submissions

    def get_all_submission_times(self, project_id):
        project = Projects.query.filter(Projects.Id == project_id).first()
        project_start_date = project.Start
        project_end_date = project.End

        blocks = [
            '12:00 AM - 2:00 AM',
            '2:00 AM - 4:00 AM',
            '4:00 AM - 6:00 AM',
            '6:00 AM - 8:00 AM',
            '8:00 AM - 10:00 AM',
            '10:00 AM - 12:00 PM',
            '12:00 PM - 2:00 PM',
            '2:00 PM - 4:00 PM',
            '4:00 PM - 6:00 PM',
            '6:00 PM - 8:00 PM',
            '8:00 PM - 10:00 PM',
            '10:00 PM - 12:00 AM'
        ]
        submissions_dict = {(project_start_date + timedelta(days=i)).strftime('%A %b %d'): {block: 0 for block in blocks} for i in range(8)}

        submissions = Submissions.query.filter(Submissions.Project == project_id).all()

        students ={}
        for submission in submissions:
            
            if submission.User not in students:
                if submission.IsPassing == 1:
                    students[submission.User] = -1
                else:
                    students[submission.User] = 1
            else:
                if submission.IsPassing == 1:
                    students[submission.User] = -1
                else:
                    if students[submission.User] != -1:
                        students[submission.User] += 1
            date = submission.Time.date()
            weekday_date = date.strftime('%A %b %d')
            hour = submission.Time.hour
            if (date < project_start_date.date()) or (date > (project_start_date.date() + timedelta(days=9))):
                continue

            if weekday_date not in submissions_dict:
                submissions_dict[weekday_date] = {block: 0 for block in blocks}

            block_index = hour // 2
            block = blocks[block_index]

            submissions_dict[weekday_date][block] += 1

        students = {student: value for student, value in students.items() if value != -1}
        students = dict(sorted(students.items(), key=lambda item: item[1], reverse=True)[:10])
        
        students_list = []
        for student_id in students:
            student = Users.query.filter(Users.Id == student_id).first()
            students_list.append([student_id,  students[student_id],student.Firstname, student.Lastname, student.Email])

        # Create a list of weekdays starting from start_weekday and ending on the day before start_weekday in the next week
        weekdays = []
        for i in range(9):
            date = project_start_date + timedelta(days=i)
            weekdays.append(date.strftime('%A %b %d'))
        submission_heatmap = []
        for weekday_date in weekdays:
            blocks = submissions_dict.get(weekday_date)
            if blocks:
                data = list(blocks.values())
                submission_heatmap.append({
                    'name': weekday_date,
                    'data': data
                })
            else:
                submission_heatmap.append({
                    'name': weekday_date,
                    'data': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
                })
        #reverse the list so that the days are in order
        submission_heatmap.reverse()

        return submission_heatmap, students_list
    
    def day_to_day_visualizer(self, project_id, user_ids):

        project = Projects.query.filter(Projects.Id == project_id).first()
        project_start_date = project.Start
        project_end_date = project.End

        dates = []
        date = project_start_date

        days_live = (project_end_date - project_start_date).days
        for i in range(days_live + 1):
            dates.append(date.strftime('%Y/%m/%d'))
            date += timedelta(days=1)
        

        passed =[0 for i in range(days_live + 1)]
        failed =[0 for i in range(days_live + 1)]
        no_submission =[0 for i in range(days_live + 1)]

        submissions = Submissions.query.filter(Submissions.Project == project_id).all()
        
        for user_Id in user_ids:
            passed_flag = False # flag to check if the user has passed the project for a given date
            submission_flag = False # flag to check if the user has submitted for a given date
            for date in dates:
                for submission in submissions:
                    if submission.Time.strftime('%Y/%m/%d') == date and submission.User == user_Id:
                        submission_flag = True
                        if submission.IsPassing:
                            passed_flag = True
                            break
                if not submission_flag:
                    no_submission[dates.index(date)] += 1
                else:
                    if passed_flag:
                        passed[dates.index(date)] += 1
                    else:
                        failed[dates.index(date)] += 1
    
        return dates, passed, failed, no_submission
    def get_all_submissions_for_user(self, user_id):
        submissions = Submissions.query.filter(Submissions.User == user_id).all()
        return submissions
    def get_project_scores(self, project_id):
        scores = MainAssignmentGrades.query.filter(MainAssignmentGrades.ProjectId == project_id).all()
        student_list = []
        for score in scores:
            student_list.append([score.UserId, score.Grade])
        return student_list
    def submitSuggestion(self, user_id, suggestion):
        suggestion_row = StudentSuggestions(
            UserId=int(user_id),
            Suggestion=str(suggestion or ""),
            SubmittedAt=datetime.now(),
        )
        db.session.add(suggestion_row)
        db.session.commit()
        return "ok"
    def save_manual_grading(self, submission_id, grade, scoring_mode, error_points, errors, error_defs, checkpoint=False, checkpoint_id=None):
        try:
            sub = Submissions.query.get(submission_id)
            if sub is None:
                return False

            sid = sub.User
            pid = sub.Project
            is_checkpoint_submission = bool(getattr(sub, "IsCheckpoint", False)) or bool(checkpoint)

            mode = scoring_mode if scoring_mode in ("perInstance", "flatPerError") else "perInstance"
            clean_pts = {}
            for k, v in ((error_points or {}).items() if isinstance(error_points, dict) else []):
                try:
                    clean_pts[str(k)] = max(0, int(v))
                except Exception:
                    pass
            points_json = json.dumps(clean_pts, sort_keys=True)

            # error_defs stores custom defs INCLUDING default points.
            defs_json = json.dumps(error_defs or {}, sort_keys=True)

            if is_checkpoint_submission:
                grades = CheckpointGrades.query.get(int(submission_id))
                if grades:
                    grades.UserId = sid
                    grades.ProjectId = pid
                    grades.Grade = int(grade) if grade is not None else grades.Grade
                    grades.ScoringMode = mode
                    grades.ErrorPointsJson = points_json
                    grades.ErrorDefsJson = defs_json
                    grades.UpdatedAt = datetime.utcnow()
                else:
                    db.session.add(CheckpointGrades(
                        SubmissionId=int(submission_id),
                        UserId=sid,
                        ProjectId=pid,
                        Grade=int(grade) if grade is not None else 0,
                        ScoringMode=mode,
                        ErrorPointsJson=points_json,
                        ErrorDefsJson=defs_json,
                        UpdatedAt=datetime.utcnow(),
                    ))
            else:
                grades = (MainAssignmentGrades.query
                    .filter(MainAssignmentGrades.UserId == sid)
                    .filter(MainAssignmentGrades.ProjectId == pid)
                    .first())

                if grades:
                    grades.Grade = int(grade) if grade is not None else grades.Grade
                    grades.SubmissionId = int(submission_id)
                    grades.ScoringMode = mode
                    grades.ErrorPointsJson = points_json
                    grades.ErrorDefsJson = defs_json
                    grades.UpdatedAt = datetime.utcnow()
                else:
                    db.session.add(MainAssignmentGrades(
                        UserId=sid,
                        ProjectId=pid,
                        Grade=int(grade) if grade is not None else 0,
                        SubmissionId=int(submission_id),
                        ScoringMode=mode,
                        ErrorPointsJson=points_json,
                        ErrorDefsJson=defs_json,
                        UpdatedAt=datetime.utcnow(),
                    ))

            # Replace error rows for this exact submission.
            SubmissionAnnotations.query.filter_by(SubmissionId=submission_id).delete()

            for error in (errors or []):
                db.session.add(SubmissionAnnotations(
                    SubmissionId=int(submission_id),
                    StartLine=int(error.get('startLine')),
                    EndLine=int(error.get('endLine')),
                    ErrorId=str(error.get('errorId')),
                    Count=max(1, int(error.get('count', 1))),
                    Note=str(error.get('note', '') or ''),
                ))

            db.session.commit()
            return True
        except Exception:
            db.session.rollback()
            return False

    def get_manual_errors(self, submission_id):

        # fetch all errors for this submission
        errors = SubmissionAnnotations.query.filter(SubmissionAnnotations.SubmissionId == submission_id).all()

        # convert to list of dicts
        return [
            {
                'startLine': e.StartLine,
                'endLine': e.EndLine,
                'errorId': e.ErrorId,
                'count': getattr(e, "Count", 1) or 1,
                'note': getattr(e, "Note", "") or ""
            }
            for e in errors
        ]

    def get_manual_grade_config(self, submission_id: int):
        """
        Return persisted manual grading config for this exact submission.

        Older non-checkpoint grades are stored on MainAssignmentGrades by (Sid, Pid), so this
        still falls back to the legacy row when no per-submission row exists.
        """
        sub = Submissions.query.get(int(submission_id))
        if sub is None:
            return {"grade": None, "scoringMode": "perInstance", "errorPoints": {}, "errorDefs": {}}

        if bool(getattr(sub, "IsCheckpoint", False)):
            row = CheckpointGrades.query.get(int(submission_id))
        else:
            sid = sub.User
            pid = sub.Project
            row = (MainAssignmentGrades.query
                .filter(MainAssignmentGrades.UserId == sid)
                .filter(MainAssignmentGrades.ProjectId == pid)
                .filter(MainAssignmentGrades.SubmissionId == int(submission_id))
                .first())

            if row is None:
                row = (MainAssignmentGrades.query
                    .filter(MainAssignmentGrades.UserId == sid)
                    .filter(MainAssignmentGrades.ProjectId == pid)
                    .first())

        if row is None:
            return {"grade": None, "scoringMode": "perInstance", "errorPoints": {}, "errorDefs": {}}

        mode = getattr(row, "ScoringMode", None)
        if mode not in ("perInstance", "flatPerError"):
            mode = "perInstance"

        raw_pts = getattr(row, "ErrorPointsJson", None) or "{}"
        try:
            pts = json.loads(raw_pts) if isinstance(raw_pts, str) else (raw_pts or {})
        except Exception:
            pts = {}

        raw_defs = getattr(row, "ErrorDefsJson", None) or "{}"
        try:
            defs = json.loads(raw_defs) if isinstance(raw_defs, str) else (raw_defs or {})
        except Exception:
            defs = {}

        return {"grade": getattr(row, "Grade", None), "scoringMode": mode, "errorPoints": pts, "errorDefs": defs}

    def _grade_payload_from_row(self, row):
        raw_pts = getattr(row, "ErrorPointsJson", None) or "{}"
        try:
            pts = json.loads(raw_pts) if isinstance(raw_pts, str) else (raw_pts or {})
        except Exception:
            pts = {}

        raw_defs = getattr(row, "ErrorDefsJson", None) or "{}"
        try:
            defs = json.loads(raw_defs) if isinstance(raw_defs, str) else (raw_defs or {})
        except Exception:
            defs = {}

        return {
            'grade': getattr(row, "Grade", None),
            'submission_id': getattr(row, "SubmissionId", None),
            'scoring_mode': getattr(row, "ScoringMode", None),
            'error_points': pts,
            'error_defs': defs
        }

    def get_manual_grade_for_submission(self, submission_id: int):
        sub = Submissions.query.get(int(submission_id))
        if sub is None:
            return None

        if bool(getattr(sub, "IsCheckpoint", False)):
            row = CheckpointGrades.query.get(int(submission_id))
        else:
            row = (MainAssignmentGrades.query
                .filter(MainAssignmentGrades.UserId == sub.User)
                .filter(MainAssignmentGrades.ProjectId == sub.Project)
                .filter(MainAssignmentGrades.SubmissionId == int(submission_id))
                .first())
            if row is None:
                row = (MainAssignmentGrades.query
                    .filter(MainAssignmentGrades.UserId == sub.User)
                    .filter(MainAssignmentGrades.ProjectId == sub.Project)
                    .first())

        if row is None:
            return None
        return self._grade_payload_from_row(row)

    def get_project_grade_info(self, project_id: int, checkpoint=False, checkpoint_id=None):
        # Get grade info for a project. Normal projects use main assignment rows.
        # Checkpoints use per-submission rows so each checkpoint can be graded separately.
        checkpoint = bool(checkpoint)

        if checkpoint:
            subs_query = Submissions.query.filter(
                Submissions.Project == int(project_id),
                Submissions.IsCheckpoint == True,
            )
            if checkpoint_id is not None:
                subs_query = subs_query.filter(Submissions.CheckpointId == int(checkpoint_id))

            latest_by_student = {}
            for sub in subs_query.order_by(Submissions.User.asc(), Submissions.Time.desc()).all():
                sid = int(getattr(sub, "User", 0) or 0)
                if sid and sid not in latest_by_student:
                    latest_by_student[sid] = sub

            submission_ids = [int(s.Id) for s in latest_by_student.values()]
            grade_rows = CheckpointGrades.query.filter(CheckpointGrades.SubmissionId.in_(submission_ids)).all() if submission_ids else []
            grades_by_submission = {int(g.SubmissionId): self._grade_payload_from_row(g) for g in grade_rows}

            grades_by_student = {}
            for sid, sub in latest_by_student.items():
                payload = grades_by_submission.get(int(sub.Id), {
                    'grade': 0,
                    'submission_id': int(sub.Id),
                    'scoring_mode': "perInstance",
                    'error_points': {},
                    'error_defs': {},
                })
                payload['submission_id'] = int(sub.Id)
                grades_by_student[sid] = payload
        else:
            grade_rows = MainAssignmentGrades.query.filter(MainAssignmentGrades.ProjectId == project_id).all()
            grades_by_student = {}
            for g in grade_rows:
                grades_by_student[g.UserId] = self._grade_payload_from_row(g)

        database_ids = list(grades_by_student.keys())
        student_numbers = Users.query.filter(Users.Id.in_(database_ids)).all() if database_ids else []
        numbers_by_student = defaultdict(str)
        for num in student_numbers:
            numbers_by_student[num.Id] = num.StudentNumber

        submission_ids = [v['submission_id'] for v in grades_by_student.values() if v.get('submission_id') is not None]
        errors = SubmissionAnnotations.query.filter(SubmissionAnnotations.SubmissionId.in_(submission_ids)).all() if submission_ids else []
        errors_by_submission = defaultdict(list)
        for e in errors:
            errors_by_submission[e.SubmissionId].append(e)

        rows = []
        for sid, data in grades_by_student.items():
            error_list = errors_by_submission.get(data['submission_id'], [])
            error_data = [{
                'errorId': getattr(e, "ErrorId", None),
                'startLine': getattr(e, "StartLine", None),
                'endLine': getattr(e, "EndLine", None),
                'count': getattr(e, "Count", None),
                'note': getattr(e, "Note", "") or ""
            } for e in error_list]

            rows.append({
                'number': numbers_by_student[sid],
                'grade': data['grade'],
                'points': data['error_points'],
                'scoring_mode': data['scoring_mode'],
                'error_defs': data['error_defs'],
                'description': error_data
            })

        return rows
